# Generated by Django 4.2.4 on 2023-08-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comentarios',
            new_name='comentario',
        ),
    ]
